spring:
  application:
    name: todo-app-mstg
  datasource:
    url: +${DATASOURCE_URL}
    username: +${DB_USER}
    password: +${DB_PASSWORD}

    #url: jdbc:postgresql://localhost:5400/TODO-DB
    #username: postgres
    #password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8098